const STORAGE_KEY='price-organizer-v1';
const DEFAULT_CATEGORIES=['食品饮料','日用百货','办公用品','电子产品','服装鞋帽','其他'];
let state=loadState(); let editingId=null;
function loadState(){try{const raw=localStorage.getItem(STORAGE_KEY);if(raw)return JSON.parse(raw)}catch(e){}return{products:[],categories:DEFAULT_CATEGORIES,history:[]}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function showToast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>el.classList.remove('show'),2600)}
function fmtDate(v){if(!v)return'—';const d=new Date(v);return isNaN(d)?v:d.toLocaleDateString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit'})}
function price(v){if(v===''||v==null||isNaN(Number(v)))return'—';return '¥ '+Number(v).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})}
function render(){renderStats();renderCategories();renderHistory();renderFilters();renderProducts();renderCategoryManage()}
function renderStats(){const p=state.products;$('#stat-total').textContent=p.length;$('#stat-categories').textContent=new Set(p.map(x=>x.category||'未分类')).size;$('#stat-suppliers').textContent=new Set(p.map(x=>x.supplier).filter(Boolean)).size;const h=state.history[0];$('#stat-last').textContent=h?fmtDate(h.time):'—';$('#stat-last-sub').textContent=h?`${h.file} · 新增 ${h.added} 条`:'等待第一张价格表'}
function renderCategories(){const counts={};state.products.forEach(p=>{const c=p.category||'未分类';counts[c]=(counts[c]||0)+1});const total=state.products.length||1;const names=[...state.categories];if(counts['未分类'])names.push('未分类');$('#category-cards').innerHTML=names.map((c,i)=>`<div class="category-card"><div class="cat-top"><span>${escapeHtml(c)}</span><span>${counts[c]||0} 件</span></div><strong>${Math.round((counts[c]||0)/total*100)}<small style="font-size:14px">%</small></strong><div class="progress"><i style="width:${Math.round((counts[c]||0)/total*100)}%"></i></div></div>`).join('')||'<div class="empty-state">导入数据后，这里会显示商品分类分布。</div>'}
function renderHistory(){const body=$('#import-history'),empty=$('#history-empty');body.innerHTML=state.history.slice(0,8).map(h=>`<tr><td><b>${escapeHtml(h.file)}</b></td><td>${fmtDate(h.time)}</td><td style="color:#258d7d">+${h.added}</td><td style="color:#b77533">${h.updated}</td><td>${h.skipped}</td></tr>`).join('');empty.style.display=state.history.length?'none':'block'}
function renderFilters(){const current=$('#category-filter').value||'all';$('#category-filter').innerHTML='<option value="all">全部分类</option>'+state.categories.map(c=>`<option value="${escapeAttr(c)}">${escapeHtml(c)}</option>`).join('');$('#category-filter').value=state.categories.includes(current)?current:'all';$('#modal-category').innerHTML=state.categories.map(c=>`<option>${escapeHtml(c)}</option>`).join('')+'<option value="">未分类</option>'}
function renderProducts(){let list=[...state.products];const q=($('#search-input')?.value||'').trim().toLowerCase();const cat=$('#category-filter')?.value||'all';const sort=$('#sort-select')?.value||'name';if(q)list=list.filter(p=>[p.name,p.sku,p.supplier,p.spec].join(' ').toLowerCase().includes(q));if(cat!=='all')list=list.filter(p=>(p.category||'')===cat);list.sort((a,b)=>sort==='price-desc'?Number(b.price||0)-Number(a.price||0):sort==='price-asc'?Number(a.price||0)-Number(b.price||0):sort==='updated'?new Date(b.updatedAt)-new Date(a.updatedAt):String(a.name).localeCompare(String(b.name),'zh-CN'));const body=$('#product-rows'),empty=$('#products-empty');body.innerHTML=list.map(p=>`<tr><td><b>${escapeHtml(p.name||'未命名商品')}</b><br><small style="color:#9aa5ac">${escapeHtml(p.sku||'无货号')}</small></td><td><span class="pill">${escapeHtml(p.category||'未分类')}</span></td><td>${escapeHtml([p.spec,p.unit].filter(Boolean).join(' / ')||'—')}</td><td>${escapeHtml(p.supplier||'—')}</td><td class="price">${price(p.price)}</td><td>${fmtDate(p.updatedAt)}</td><td><button class="row-action" data-edit="${p.id}">编辑</button></td></tr>`).join('');empty.style.display=list.length?'none':'block'}
function renderCategoryManage(){const counts={};state.products.forEach(p=>{const c=p.category||'未分类';counts[c]=(counts[c]||0)+1});$('#category-manage-list').innerHTML=state.categories.map((c,i)=>`<div class="manage-row"><i class="cat-color" style="background:${['#1d8c83','#f1a452','#6a7bd1','#cf6a8b','#7c9f61','#8b7aa8'][i%6]}"></i><strong>${escapeHtml(c)}</strong><span>${counts[c]||0} 个商品</span><button class="row-action" data-rename="${escapeAttr(c)}">重命名</button><button class="row-action" data-delete-cat="${escapeAttr(c)}">删除</button></div>`).join('')||'<div class="empty-state">还没有分类。</div>'}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}function escapeAttr(v){return escapeHtml(v)}
function normalizeRow(r,source){const get=(...keys)=>{const k=Object.keys(r).find(x=>keys.some(key=>x.trim().toLowerCase().replace(/[\s_\-]/g,'')===key));return k?r[k]:''};const name=String(get('商品名称','商品','产品名称','名称','name','productname')).trim();if(!name)return null;let cat=String(get('分类','类别','品类','category')).trim();if(!state.categories.includes(cat))cat=autoCategory(name)||cat;return{id:'',name,sku:String(get('货号','商品编码','sku','编码','编号')).trim(),category:cat,spec:String(get('规格','型号','规格型号','spec')).trim(),unit:String(get('单位','unit')).trim(),price:cleanNumber(get('价格','单价','含税单价','price','售价')),supplier:String(get('供应商','厂家','品牌','supplier')).trim(),effectiveDate:String(get('生效日期','日期','报价日期','date')).trim(),sourceFile:source,updatedAt:new Date().toISOString()}}
function cleanNumber(v){if(v===null||v===undefined||v==='')return'';const n=Number(String(v).replace(/[¥￥,\s]/g,''));return isNaN(n)?String(v):n}function autoCategory(name){const rules=[['食品饮料',['食品','饮料','零食','酒','茶','咖啡','粮','水果']],['日用百货',['清洁','纸巾','洗','日用','家居','生活']],['办公用品',['办公','文具','打印','文件夹','笔']],['电子产品',['电脑','手机','耳机','键盘','鼠标','电子','显示器']],['服装鞋帽',['服装','鞋','帽','衣','裤','袜']]];for(const [c,words]of rules)if(words.some(w=>name.includes(w)))return c;return''}
function uniqueKey(p){return(p.sku||`${p.name}|${p.spec}|${p.supplier}`).toLowerCase().replace(/\s/g,'')}
function importRows(rows,file){let added=0,updated=0,skipped=0;rows.forEach(r=>{const p=normalizeRow(r,file);if(!p)return;const key=uniqueKey(p);const idx=state.products.findIndex(x=>uniqueKey(x)===key);if(idx<0){p.id=crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random();state.products.push(p);added++}else{const old=state.products[idx];state.products[idx]={...old,...p,id:old.id,category:p.category||old.category,updatedAt:new Date().toISOString()};updated++}});if(!rows.length)skipped++;state.history.unshift({file,time:new Date().toISOString(),added,updated,skipped});save();render();showToast(`已合并：新增 ${added} 条，更新 ${updated} 条`)}
function parseCsv(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());if(!lines.length)return[];const delim=lines[0].includes('\t')?'\t':',';const split=s=>{const out=[];let cur='',quote=false;for(let i=0;i<s.length;i++){const ch=s[i];if(ch==='"'&&s[i+1]==='"'){cur+='"';i++}else if(ch==='"')quote=!quote;else if(ch===delim&&!quote){out.push(cur.trim());cur=''}else cur+=ch}out.push(cur.trim());return out};const heads=split(lines[0]);return lines.slice(1).map(l=>{const cells=split(l),o={};heads.forEach((h,i)=>o[h]=cells[i]??'');return o})}
async function handleFiles(files){for(const file of files){try{if(window.XLSX&&/\.xlsx?$/i.test(file.name)){const data=await file.arrayBuffer(),wb=XLSX.read(data,{type:'array'});const rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});importRows(rows,file.name)}else{const text=await file.text();importRows(parseCsv(text),file.name)}}catch(e){showToast(`${file.name} 读取失败，请检查文件格式`)}}}
function exportExcel(){if(!state.products.length){showToast('暂无商品可导出');return}if(!window.XLSX){showToast('Excel 导出组件未加载，请联网后重试');return}const wb=XLSX.utils.book_new();const groups={};state.products.forEach(p=>(groups[p.category||'未分类']??=[]).push(p));Object.entries(groups).forEach(([cat,items])=>{const rows=items.map(p=>({'商品名称':p.name,'货号 / SKU':p.sku,'分类':p.category,'规格':p.spec,'单位':p.unit,'价格':p.price,'供应商':p.supplier,'生效日期':p.effectiveDate,'来源文件':p.sourceFile,'最近更新':fmtDate(p.updatedAt)}));const ws=XLSX.utils.json_to_sheet(rows);ws['!cols']=[{wch:24},{wch:16},{wch:14},{wch:18},{wch:10},{wch:12},{wch:20},{wch:14},{wch:24},{wch:14}];XLSX.utils.book_append_sheet(wb,ws,cat.slice(0,31)||'未分类')});const all=XLSX.utils.json_to_sheet(state.products.map(p=>({'商品名称':p.name,'货号 / SKU':p.sku,'分类':p.category||'未分类','规格':p.spec,'单位':p.unit,'价格':p.price,'供应商':p.supplier,'生效日期':p.effectiveDate,'来源文件':p.sourceFile,'最近更新':fmtDate(p.updatedAt)})));XLSX.utils.book_append_sheet(wb,all,'全部商品');XLSX.writeFile(wb,`价格表整合_${new Date().toISOString().slice(0,10)}.xlsx`);showToast('Excel 已导出')}
function openEditor(id){editingId=id;const p=state.products.find(x=>x.id===id);if(!p)return;const form=$('#product-form');Object.keys(p).forEach(k=>{if(form.elements[k])form.elements[k].value=p[k]??''});$('#modal').classList.remove('hidden')}
function switchView(view){$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$$('.view').forEach(v=>v.classList.toggle('active-view',v.id===view+'-view'));$('#page-title').textContent=view==='overview'?'价格表总览':view==='products'?'商品库':'分类管理'}
$('#upload-trigger').onclick=()=>$('#file-input').click();$('#products-upload').onclick=()=>$('#file-input').click();$('#file-input').onchange=e=>handleFiles([...e.target.files]);$('#export-btn').onclick=exportExcel;$('#search-input').oninput=renderProducts;$('#category-filter').onchange=renderProducts;$('#sort-select').onchange=renderProducts;$$('.nav-item').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$('[data-view-target]').forEach(b=>b.onclick=()=>switchView(b.dataset.viewTarget));$('#clear-data').onclick=()=>{if(confirm('确定清空本机保存的全部价格表数据吗？')){state={products:[],categories:DEFAULT_CATEGORIES,history:[]};save();render();showToast('数据已清空')}};$('#add-category').onclick=()=>{const c=prompt('请输入新分类名称');if(c&&c.trim()&&!state.categories.includes(c.trim())){state.categories.push(c.trim());save();render();showToast('分类已创建')}};document.addEventListener('click',e=>{const edit=e.target.closest('[data-edit]');if(edit)openEditor(edit.dataset.edit);const rename=e.target.closest('[data-rename]');if(rename){const next=prompt('请输入新的分类名称',rename.dataset.rename);if(next&&next.trim()&&next.trim()!==rename.dataset.rename&&!state.categories.includes(next.trim())){state.products.forEach(p=>{if(p.category===rename.dataset.rename)p.category=next.trim()});state.categories[state.categories.indexOf(rename.dataset.rename)]=next.trim();save();render();showToast('分类已重命名')}}const del=e.target.closest('[data-delete-cat]');if(del&&confirm(`删除分类“${del.dataset.deleteCat}”？商品会变为未分类。`)){state.products.forEach(p=>{if(p.category===del.dataset.deleteCat)p.category=''});state.categories=state.categories.filter(c=>c!==del.dataset.deleteCat);save();render();showToast('分类已删除')}});$('#modal-close').onclick=()=>$('#modal').classList.add('hidden');$('#modal-cancel').onclick=()=>$('#modal').classList.add('hidden');$('#product-form').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target).entries());const idx=state.products.findIndex(p=>p.id===editingId);if(idx>=0){state.products[idx]={...state.products[idx],...data,price:cleanNumber(data.price),updatedAt:new Date().toISOString()};save();render();$('#modal').classList.add('hidden');showToast('商品已保存')}};render();
